apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: demo
  annotations:
    kubernetes.io/changes-cause: "demo-service"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-service
          image: sagiransari/demo-service-v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "756Mi"
              cpu: "0.5"